changelog:
  exclude:
    labels:
      - skip-changelog
      - documentation-only
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - '*'
