#!/usr/bin/env python3
"""Validate ROMCNV translations and emit portable generated C string tables."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import build_translations


ROOT = Path(__file__).resolve().parents[1]
TRANSLATIONS_DIR = ROOT / "translations/romcnv"
LANGUAGE_FILES = {
    "en": "en.lang",
    "zh-Hans": "zh-Hans.lang",
}


class RomcnvTranslationError(RuntimeError):
    pass


def parse_manifest(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise RomcnvTranslationError(f"missing stable manifest: {path}") from exc

    entries: list[tuple[int, str]] = []
    for line_no, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = re.fullmatch(
            r"ROMCNV_TEXT_ID\(\s*([A-Za-z_]\w*)\s*,\s*(\d+)\s*\)", stripped
        )
        if not match:
            raise RomcnvTranslationError(
                f"{path}:{line_no}: unsupported manifest line: {stripped!r}"
            )
        entries.append((int(match.group(2)), match.group(1)))

    entries.sort()
    ids = [entry_id for entry_id, _name in entries]
    if not entries or ids != list(range(len(entries))):
        raise RomcnvTranslationError("ROMCNV message IDs must be contiguous from zero")
    names = [name for _entry_id, name in entries]
    if len(names) != len(set(names)):
        raise RomcnvTranslationError("ROMCNV manifest contains duplicate names")
    return names


def load_and_validate_sources(
    directory: Path,
) -> tuple[list[str], dict[str, dict[str, bytes | None]]]:
    names = parse_manifest(directory / "messages.def")
    expected = set(names)
    catalogs: dict[str, dict[str, bytes | None]] = {}

    for language, filename in LANGUAGE_FILES.items():
        order, catalog = build_translations.parse_language_source(directory / filename)
        actual = set(catalog)
        missing = [name for name in names if name not in actual]
        unknown = sorted(actual - expected)
        if missing:
            raise RomcnvTranslationError(f"{filename}: missing keys: {', '.join(missing)}")
        if unknown:
            raise RomcnvTranslationError(f"{filename}: unknown keys: {', '.join(unknown)}")
        if order != names:
            raise RomcnvTranslationError(
                f"{filename}: keys must follow translations/romcnv/messages.def order"
            )
        catalogs[language] = catalog

    english = catalogs["en"]
    for name in names:
        expected_contract = build_translations.printf_contract(english[name], f"en:{name}")
        for language in LANGUAGE_FILES:
            actual_contract = build_translations.printf_contract(
                catalogs[language][name], f"{language}:{name}"
            )
            if actual_contract != expected_contract:
                raise RomcnvTranslationError(
                    f"{language}:{name}: printf contract {actual_contract} does not match "
                    f"English {expected_contract}"
                )
    return names, catalogs


def c_string_literal(value: bytes | None) -> str:
    if value is None:
        return "NULL"
    out: list[str] = ['"']
    escapes = {
        0x09: r"\t",
        0x0A: r"\n",
        0x0D: r"\r",
        0x22: r'\"',
        0x5C: r"\\",
    }
    for byte in value:
        if byte in escapes:
            out.append(escapes[byte])
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append(f"\\{byte:03o}")
    out.append('"')
    return "".join(out)


def render_generated_include(
    names: list[str], catalogs: dict[str, dict[str, bytes | None]]
) -> str:
    lines = ["/* Generated by tools/build_romcnv_translations.py; do not edit. */", ""]
    for language, symbol in (("en", "en"), ("zh-Hans", "zh_hans")):
        lines.append(
            f"static const char *const romcnv_catalog_{symbol}[ROMCNV_TEXT_COUNT] = {{"
        )
        for name in names:
            lines.append(f"\t{c_string_literal(catalogs[language][name])}, /* {name} */")
        lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--translations-dir", type=Path, default=TRANSLATIONS_DIR)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    try:
        names, catalogs = load_and_validate_sources(args.translations_dir)
        generated = render_generated_include(names, catalogs)
    except (RomcnvTranslationError, build_translations.TranslationError) as exc:
        print(f"ROMCNV translation validation failed: {exc}", file=sys.stderr)
        return 1

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            args.output.write_text(generated, encoding="utf-8")

    sizes = ", ".join(
        f"{language}={sum(len(value) for value in catalog.values() if value is not None)} B"
        for language, catalog in catalogs.items()
    )
    print(f"validated {len(names)} ROMCNV keys in {len(catalogs)} languages; {sizes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
