set(NJEMU_VERSION_FALLBACK "2.4.0")

function(_njemu_version_parse_semver version prefix)
    if(NOT "${version}" MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-([0-9A-Za-z-]+)(\\.([0-9A-Za-z-]+))*)?(\\+([0-9A-Za-z-]+)(\\.([0-9A-Za-z-]+))*)?$")
        message(FATAL_ERROR "not a Semantic Version: '${version}'")
    endif()
    set(_major "${CMAKE_MATCH_1}")
    set(_minor "${CMAKE_MATCH_2}")
    set(_patch "${CMAKE_MATCH_3}")
    foreach(_part IN ITEMS _major _minor _patch)
        if(${_part} MATCHES "^0[0-9]+$")
            message(FATAL_ERROR "not a Semantic Version: '${version}'")
        endif()
    endforeach()
    set(${prefix}_MAJOR "${_major}" PARENT_SCOPE)
    set(${prefix}_MINOR "${_minor}" PARENT_SCOPE)
    set(${prefix}_PATCH "${_patch}" PARENT_SCOPE)
endfunction()

function(_njemu_git source_dir output_var)
    set(_args ${ARGN})
    execute_process(
        COMMAND "${_NJEMU_GIT_EXECUTABLE}" -C "${source_dir}" ${_args}
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _output
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(_result EQUAL 0)
        set(${output_var} "${_output}" PARENT_SCOPE)
    else()
        set(${output_var} "" PARENT_SCOPE)
    endif()
endfunction()

function(njemu_derive_version source_dir)
    get_filename_component(_source_dir "${source_dir}" ABSOLUTE)
    _njemu_version_parse_semver("${NJEMU_VERSION_FALLBACK}" _fallback)

    set(_override "")
    if(DEFINED NJEMU_VERSION_OVERRIDE AND NOT "${NJEMU_VERSION_OVERRIDE}" STREQUAL "")
        set(_override "${NJEMU_VERSION_OVERRIDE}")
    elseif(DEFINED ENV{NJEMU_VERSION_OVERRIDE} AND NOT "$ENV{NJEMU_VERSION_OVERRIDE}" STREQUAL "")
        set(_override "$ENV{NJEMU_VERSION_OVERRIDE}")
    endif()

    if(NOT "${_override}" STREQUAL "")
        _njemu_version_parse_semver("${_override}" _override_parts)
        set(_version "${_override}")
        set(_release_version "${_override_parts_MAJOR}.${_override_parts_MINOR}.${_override_parts_PATCH}")
        set(_major "${_override_parts_MAJOR}")
        set(_minor "${_override_parts_MINOR}")
        set(_patch "${_override_parts_PATCH}")
        set(_sha "override")
        set(_commits 0)
        set(_dirty FALSE)
        set(_exact FALSE)
        set(_source "override")
    else()
        unset(_NJEMU_GIT_EXECUTABLE CACHE)
        unset(_NJEMU_GIT_EXECUTABLE)
        find_program(_NJEMU_GIT_EXECUTABLE NAMES git)
        if(_NJEMU_GIT_EXECUTABLE)
            _njemu_git("${_source_dir}" _inside rev-parse --is-inside-work-tree)
        else()
            set(_inside "")
        endif()

        if(NOT "${_inside}" STREQUAL "true")
            set(_version "${NJEMU_VERSION_FALLBACK}+source")
            set(_release_version "${NJEMU_VERSION_FALLBACK}")
            set(_major "${_fallback_MAJOR}")
            set(_minor "${_fallback_MINOR}")
            set(_patch "${_fallback_PATCH}")
            set(_sha "unknown")
            set(_commits 0)
            set(_dirty FALSE)
            set(_exact FALSE)
            set(_source "archive")
        else()
            _njemu_git("${_source_dir}" _sha rev-parse --short=8 HEAD)
            if("${_sha}" STREQUAL "")
                set(_sha "unknown")
            endif()
            _njemu_git("${_source_dir}" _dirty_output status --porcelain --untracked-files=no)
            if("${_dirty_output}" STREQUAL "")
                set(_dirty FALSE)
            else()
                set(_dirty TRUE)
            endif()

            _njemu_git("${_source_dir}" _tags
                for-each-ref --merged=HEAD "--format=%(refname:short)" refs/tags)
            string(REPLACE "\n" ";" _tag_list "${_tags}")
            set(_found_tag FALSE)
            set(_best_tag "")
            set(_best_count 0)
            set(_best_timestamp 0)
            foreach(_tag IN LISTS _tag_list)
                if("${_tag}" MATCHES "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
                    _njemu_git("${_source_dir}" _count rev-list --count "${_tag}..HEAD")
                    _njemu_git("${_source_dir}" _timestamp log -1 --format=%ct "${_tag}")
                    if(NOT "${_count}" STREQUAL "" AND NOT "${_timestamp}" STREQUAL "")
                        if(NOT _found_tag
                            OR _count LESS _best_count
                            OR (_count EQUAL _best_count AND _timestamp GREATER _best_timestamp)
                            OR (_count EQUAL _best_count AND _timestamp EQUAL _best_timestamp
                                AND "${_tag}" STRLESS "${_best_tag}"))
                            set(_found_tag TRUE)
                            set(_best_tag "${_tag}")
                            set(_best_count "${_count}")
                            set(_best_timestamp "${_timestamp}")
                        endif()
                    endif()
                endif()
            endforeach()

            if(NOT _found_tag)
                _njemu_git("${_source_dir}" _commits rev-list --count HEAD)
                if("${_commits}" STREQUAL "")
                    set(_commits 0)
                endif()
                set(_major "${_fallback_MAJOR}")
                set(_minor "${_fallback_MINOR}")
                set(_patch "${_fallback_PATCH}")
                set(_release_version "${NJEMU_VERSION_FALLBACK}")
                set(_metadata "g${_sha}")
                if(_dirty)
                    string(APPEND _metadata ".dirty")
                endif()
                set(_version "${NJEMU_VERSION_FALLBACK}-pre.${_commits}+${_metadata}")
                set(_exact FALSE)
                set(_source "git-no-semver-tag")
            else()
                string(SUBSTRING "${_best_tag}" 1 -1 _release_version)
                _njemu_version_parse_semver("${_release_version}" _tag_parts)
                set(_major "${_tag_parts_MAJOR}")
                set(_minor "${_tag_parts_MINOR}")
                set(_patch "${_tag_parts_PATCH}")
                set(_commits "${_best_count}")
                if(_commits EQUAL 0 AND NOT _dirty)
                    set(_exact TRUE)
                    set(_version "${_release_version}")
                else()
                    set(_exact FALSE)
                    set(_metadata "${_commits}.g${_sha}")
                    if(_dirty)
                        string(APPEND _metadata ".dirty")
                    endif()
                    set(_version "${_release_version}+${_metadata}")
                endif()
                set(_source "git-tag")
            endif()
        endif()
    endif()

    foreach(_pair IN ITEMS
            "NJEMU_VERSION;${_version}"
            "NJEMU_RELEASE_VERSION;${_release_version}"
            "NJEMU_VERSION_MAJOR;${_major}"
            "NJEMU_VERSION_MINOR;${_minor}"
            "NJEMU_VERSION_PATCH;${_patch}"
            "NJEMU_GIT_SHA;${_sha}"
            "NJEMU_COMMITS_SINCE_TAG;${_commits}"
            "NJEMU_VERSION_DIRTY;${_dirty}"
            "NJEMU_VERSION_EXACT_TAG;${_exact}"
            "NJEMU_VERSION_SOURCE;${_source}")
        list(GET _pair 0 _name)
        list(GET _pair 1 _value)
        set(${_name} "${_value}" PARENT_SCOPE)
    endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT DEFINED NJEMU_SOURCE_DIR OR "${NJEMU_SOURCE_DIR}" STREQUAL "")
        set(NJEMU_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
    endif()
    njemu_derive_version("${NJEMU_SOURCE_DIR}")
    if(DEFINED NJEMU_VERSION_OUTPUT_FILE AND NOT "${NJEMU_VERSION_OUTPUT_FILE}" STREQUAL "")
        file(WRITE "${NJEMU_VERSION_OUTPUT_FILE}" "${NJEMU_VERSION}\n")
    else()
        message("${NJEMU_VERSION}")
    endif()
endif()
